### ISSUE TITLE
Unnecessary CPU Support

### ISSUE THREAD

**Issue by ghost** [MajorGamerJay/kernel-config#1]
**On**: [config#L326-L330](https://github.com/MajorGamerJay/kernel-config/blob/master/5.11.0-gentoo-hentai-edition/config#L326-L330)

Why do you have enabled CPU Support for all those CPU's. I strongly believe that you intend do build & use that config for a single processor (AMD/INTEL) that you personally use.

**Comment by majorgamerjay** [comment]
> **On**: [config#L326-L330](https://github.com/MajorGamerJay/kernel-config/blob/master/5.11.0-gentoo-hentai-edition/config#L326-L330)
> 
> Why do you have enabled CPU Support for all those CPU's. I strongly believe that you intend do build & use that config for a single processor (AMD/INTEL) that you personally use.

I just enabled/disabled required modules with the default x86_64 config. Didn't give much thought to actually editing the config. Thanks for pointing out.
